#!/bin/bash

if [ "x`/bin/hostname`" == "xjupiter" ]
then
	echo "Mounting NFS on Mint19"
	ssh mike@mint19 'sudo mount jupiter:/home/mike/wdir /home/mike/wdir'
	ssh mike@mint19 'sudo mount jupiter:/home/mike/openmpi-4.0.0 /home/mike/openmpi-4.0.0'
fi
